name: Lint

on: ["push","pull_request"]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/iron
      - name: npm install
        run: npm install
      - name: run lint
        run: npm run lint